# systemd tmpfiles.d configuration for flux-vprint / python-validity
# Ensures /run/python-validity exists across reboots and has necessary firmware

d /run/python-validity 0755 root root -
L+ /run/python-validity/6_07f_lenovo_mis_qm.xpfwext - - - - /usr/share/python-validity/6_07f_lenovo_mis_qm.xpfwext
L+ /run/python-validity/6_07f_Lenovo.xpfwext - - - - /usr/share/python-validity/6_07f_Lenovo.xpfwext

